apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice-service-container
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notice-service
  template:
    metadata:
      labels:
        app: notice-service
    spec:
      containers:
        - name: notice-service-container
          image: ghcr.io/maengchanho/notice-service:latest
          ports:
            - containerPort: 5004
      imagePullSecrets:
        - name: ghcr-secrets