apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notice-service
  template:
    metadata:
      labels:
        app: notice-service
    spec:
      containers:
        - name: notice-service
          image: ghcr.io/maengchanho/notice-service:latest
          ports:
            - containerPort: 5004
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      imagePullSecrets:
        - name: ghcr-secrets