apiVersion: v1
kind: Service
metadata:
  name: notice-service
spec:
  selector:
    app: notice-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
      nodePort: 30011
  type: NodePort