apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: notice-service-applicationset
  namespace: default
spec:
  generators:
    - git:
        elements:
          - name: notice-service-appset
            repoURL: 'git@github.com:maengchanho/notice.git'
            revision: main
            path: 'k8s'
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true