apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notice-service-hpa
  namespace: notice-service
spec:
  scaleTargetRef:
      kind: Deployment
      name: deployment_manifest.yml
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30